
[functions.hermes-race-bridge]
enabled = true
verify_jwt = false
import_map = "./functions/hermes-race-bridge/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hermes-race-bridge/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hermes-race-bridge/*.html" ]

[functions.sync-race-data]
enabled = true
verify_jwt = false
import_map = "./functions/sync-race-data/deno.json"
entrypoint = "./functions/sync-race-data/index.ts"

[functions.race-lifecycle]
enabled = true
verify_jwt = false
import_map = "./functions/race-lifecycle/deno.json"
entrypoint = "./functions/race-lifecycle/index.ts"

[functions.blog-media-upload]
enabled = true
verify_jwt = false
import_map = "./functions/blog-media-upload/deno.json"
entrypoint = "./functions/blog-media-upload/index.ts"

[functions.site-build-bridge]
enabled = true
verify_jwt = false
import_map = "./functions/site-build-bridge/deno.json"
entrypoint = "./functions/site-build-bridge/index.ts"
